### PR TITLE
Pypi package

### PR DESCRIPTION
**Pull request by ad-m**

### CODE REVIEW

**Comment by domibarton** [comment]
Hey @ad-m, this is amazing, thanks :)
Wouldn't you add your name to the contributors list?

**Comment by ad-m** [comment]
@domibarton , i do not care about that.

**Comment by philippeowagner** [comment]
Better add your name @ad-m, otherwise @domibarton will not merge this and there will be no packages on the PyPI. 😂

**Comment by domibarton** [comment]
@philippeowagner haha good one ;) Sorry, I'm quite busy and can't find the time to manage the repo, because of that it isn't merged. 

However, got your mail as reminder. I'll have a look at it this morning and I'll merge it! Sorry!

**Comment by philippeowagner** [comment]
There's no need for an apology. Thank you for sharing this.

**Pull request merged**
